"""
models/journal.py — Saved AI trade setups with automatic outcome tracking.

Each row is a trade setup generated by /api/scanner/setup and saved by the user.
Outcome is checked on-the-fly at read time against subsequent price candles.
"""

from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Float, Integer, String, Text

from app.database import Base


class JournalEntry(Base):
    __tablename__ = "journal_entries"

    id           = Column(Integer, primary_key=True)
    created_at   = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    symbol       = Column(String(20),  nullable=False)
    bias         = Column(String(10),  nullable=False)   # "long" or "short"
    entry_low    = Column(Float,       nullable=False)
    entry_high   = Column(Float,       nullable=False)
    stop_loss    = Column(Float,       nullable=False)
    take_profit1 = Column(Float,       nullable=False)
    take_profit2 = Column(Float,       nullable=False)
    take_profit3 = Column(Float,       nullable=False)
    risk_reward  = Column(Float,       nullable=False)
    reasoning    = Column(Text,        nullable=False)
    key_risks    = Column(Text,        nullable=False)
    scanner_bias = Column(String(10))
    notes        = Column(Text,        nullable=True)
